# Generated by Django 5.2.1 on 2025-05-22 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер стола')),
                ('seats', models.PositiveIntegerField(verbose_name='Кол-во мест')),
            ],
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.table'),
        ),
    ]
