# Generated by Django 5.2.1 on 2025-06-05 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bookingrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.tablebooking'),
        ),
    ]
