# Generated by Django 5.2.1 on 2025-06-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_order_booking'),
    ]

    operations = [
    ]
